-- AlterTable
ALTER TABLE "Artist" ADD COLUMN "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Artist" ADD COLUMN "updatedAt" DATETIME;

-- AlterTable
ALTER TABLE "Label" ADD COLUMN "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Label" ADD COLUMN "updatedAt" DATETIME;

-- AlterTable
ALTER TABLE "User" ADD COLUMN "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN "updatedAt" DATETIME;
