name: Server ci/cd

on:
  push:
    branches: [master]
    paths:
      - "workspaces/server/**"
  pull_request:
    branches: [master]
    paths:
      - "workspaces/server/**"
    types: [opened, synchronize]
  
jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm
      - name: Install dependencies
        run: npm ci

  lint:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Linter
        run: npm run lint:server

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:server

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com"
          rollbackonhealthcheckfailed: true